version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-cinema

  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    ports:
      - 6380:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - microservice-cinema

volumes:
  postgres_data:
  redis_data:

networks:
  microservice-cinema: